### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/vercel/path0/app/database/.db.json.tmp'

### ISSUE THREAD

**Issue by PassionZale** [eliseekn/nextjs-fullstack-app#1]
Hello! I also use `lowdb` and deploy on `vercel`, but get some error in Production like:

```shell
Error: ENOENT: no such file or directory, open '/vercel/path0/app/database/.db.json.tmp'
```

I'm using `nextjs@14` + `app routes`.

Have you ever encountered this problem?

![image](https://github.com/user-attachments/assets/201717ad-33dc-4b22-aea3-e274fc352bc8)

**Comment by eliseekn** [comment]
Hello. I don't think vercel allows using lowdb on production. You should try one of the provided db service on vercel. Follow this link for more information : [https://nextjs.org/learn/dashboard-app/setting-up-your-database](url).

**Comment by PassionZale** [comment]
I resolved file writable in vercel.

Can I share it with you?

```ts
const __dirname = dirname(fileURLToPath(import.meta.url));

const file = join(__dirname, "db.json");
```

the `db.json` file won't be included in `PRODUCTION`, after change `next.config.mjs`:

```diff
/** @type {import('next').NextConfig} */
const nextConfig = {
+  experimental: {
+    outputFileTracingIncludes: {
+      "/api/users/[id]": ["./app/database/**/*.json"],
+    },
+  },
};
```

`db.json` is included in `PRODUCTION`, and works well.

> I don't think vercel allows using lowdb on production

You are right! After I redeploy, API **read** `db.json` is ok, but faild to **write**,

It's because of **Serverless Functions have a read-only filesystem**.

After I read vercel docs: [File system support](https://vercel.com/docs/functions/runtimes#file-system-support)

if Serverless Functions choose `Nodejs`, there's a **500MB writable folder `/tmp`**, so I changed `db.json` file path:

```diff
const __dirname = dirname(fileURLToPath(import.meta.url));

+ const file =
+  process.env.NODE_ENV === "production"
+    ? join("/tmp/db.json")
+    : join(__dirname, "db.json");
```

> /tmp folder is just `/tmp`, not `./tmp` or other path.

After I redeploy, **write** is ok.

> Of course, `db.json` will be reset after redeploy!

**Comment by eliseekn** [comment]
Nice good job 👌
